### ISSUE TITLE
Version 0.2.3 is reporting a trojan virus

### ISSUE THREAD

**Issue by grizzie17** [benlye/flash-multi#13]

**Comment by benlye** [comment]
I can assure you that there isn't anything malicious in the code. 

Which download file fot flagged? What AV product are you using? Can you report a false positive detection to the vendor?

**Comment by benlye** [comment]
I've submitted a false positive report to Microsoft.  Last time I had to do this they turned it around pretty quickly.

If you're worried you can download the .zip file instead, which is not getting flagged by Windows Defender.

**Comment by benlye** [comment]
Microsoft have confirmed that the false detection will be removed in the next Windows Defender update.
