### ISSUE TITLE
USB Device Driver Failure

### ISSUE THREAD

**Issue by loeschr** [benlye/flash-multi#26]
Running Win10 2004.  Fresh install of Flash Multi v0.4.3.  Tried to install USB device drivers and get verbose error -

".\drivers\wdi-simple.exe --vid 0x1EAF --pid 0x0004 --type 3 --name "MULTI-Module USB Serial" --dest "C:\Users\Robert\AppData\Local\Temp\1k03e3yi.tpm\MULTI-USB-Serial" --progressbar=5966042
The system cannot find the file specified
.\drivers\wdi-simple.exe --vid 0x1EAF --pid 0x0003 --type 2 --name "MULTI-Module DFU Bootloader" --dest "C:\Users\Robert\AppData\Local\Temp\1k03e3yi.tpm\MULTI-DFU-Bootloader" --progressbar=5966042
The system cannot find the file specified"

If I try to write the firmware to my Jumper T16 Pro internal card I get the following error which is probably related to the driver issue, but may provide some information -

".\tools\stm32flash.exe -o -S 0x8000000:129024 -b 115200 COM3

.\tools\stm32flash.exe does not exist"

Any assistance on getting the drivers installed would be appreciated.  The USB-to-Serial board is being recognized by Win10 as COM3.

**Comment by benlye** [comment]
Either you have not extracted all the files from the zip file, or your anti virus software has removed or quarantined them.
