### ISSUE TITLE
USB Supporting Warning Message

### ISSUE THREAD

**Issue by dayue1984** [benlye/flash-multi#34]
I've updated my irangx 4in1 to the new bootloader, then I want to update the firmware, and always get this message, but where is the OK button? I can‘t even close this MsgBox. Thanks!
![msg](https://user-images.githubusercontent.com/34289866/104105737-24048400-52eb-11eb-8879-958fb22ce3be.PNG)

**Comment by benlye** [comment]
What version of Windows are you running? What language is your OS?

**Comment by dayue1984** [comment]
> What version of Windows are you running? What language is your OS?

I'm running the latest Windows10 20H2, system display language is Simplified Chinese. Thanks!

**Comment by benlye** [comment]
Thanks, I'll try to reproduce.

**Comment by benlye** [comment]
I think I've found the problem.  I need to work on a better solution and maybe use a different font which has a better fallback on non-English systems, but this test version should display the dialog box correctly for you so you can update your module.

[No-Font-Scaling.zip](https://github.com/benlye/flash-multi/files/5791736/No-Font-Scaling.zip)

(The only other change from 0.5.1 is that the bootloader type option is removed - the new 'Sticky DFU' bootloader is always enabled.)

**Comment by dayue1984** [comment]
It’s working, thanks alot!

2021年1月10日 04:04，Ben Lye <notifications@github.com<mailto:notifications@github.com>> 写道：



I think I've found the problem. I need to work on a better solution and maybe use a different font which has a better fallback on non-English systems, but this test version should display the dialog box correctly for you so you can update your module.

No-Font-Scaling.zip<https://github.com/benlye/flash-multi/files/5791736/No-Font-Scaling.zip>

(The only other change from 0.5.1 is that the bootloader type option is removed - the new 'Sticky DFU' bootloader is always enabled.)

**Comment by benlye** [comment]
Fixed in latest release.
