### ISSUE TITLE
flash multi c'an't read module 

### ISSUE THREAD

**Issue by horjab** [benlye/flash-multi#54]
I hope that somebody is still reading this and I will be very grateful for your help. 
The module is Jumper 4IN1 SE external.*
Version 1.2.1.25.
I read a lot on the  manuals on github and rcgroups .
I have installed the flash multi and the drivers. 
I checked the com port . I connected the USB cable green led it' on. I tried to write and I got a failed message.
I tried also with the module in to the radio and powered on with the same result
![Multi 1](https://github.com/benlye/flash-multi/assets/57867022/fde5f697-45ab-4983-8b76-7acbf0696674)
![Multi 2](https://github.com/benlye/flash-multi/assets/57867022/518288ec-2af8-44ce-8f19-5f413b067cc5)
Thank you 
Horjab

**Comment by benlye** [comment]
Please tick the 'Show verbose output' box and show the post the verbose logs.
