### ISSUE TITLE
windows 11 driver question

### ISSUE THREAD

**Issue by beau76** [benlye/flash-multi#58]
Hi I have the radio master multi  4 in1  external I am running Windows 11 and when I look in the device manager you can see how the device is showing up what do I need to install to make this work I am trying to update the boot loader on my multi-module I have tried installing the drivers this is the software that they did not seem to do anything

![image](https://github.com/benlye/flash-multi/assets/38789686/3339758d-cd53-45b1-beea-c7da6074bb13)

**Comment by benlye** [comment]
You need to install the Silabs CP210x driver.

https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers

**Comment by beau76** [comment]
Do I want the vcp driver or do I want the universal

**Comment by benlye** [comment]
Universal

**Comment by beau76** [comment]
Does this mean the module already has the new bootloader on it or do I need to flash it via the USB for the bootloader to be changed?

when I do the boot loader When you say unplug do you mean just the USB cable  or does the whole module have to be unplug from the radio

![image](https://github.com/benlye/flash-multi/assets/38789686/a956131c-09b1-4f56-87f6-2157ad26b890)

**Comment by benlye** [comment]
On a module like yours you don't need to independently update the bootloader - it gets rewritten every time you flash the firmware.

All you need to do is flash the latest (or any) firmware and the bootloader is also written.

It probably already has the latest bootloader on it, but updating it one time with Flash Multi will make sure.
