### ISSUE TITLE
Irangex nano pl18 edgetx

### ISSUE THREAD

**Issue by swemiklan** [benlye/flash-multi#59]
Flasht edgetx to pl18 ( no hardware mod ) installd new nano module and tryed to bind. no luck.
Edgetx show ( no multi telemetry detected ) in model page and radio information.
Flash module wiht 1.3.3.33 managede after some trubble dfu mode/ usb i can read firmware of module trou flashmulti 6,1
still no luck binding, sam text in edgetx. Now i am not able to read module wiht flashmulti, module led are solid green and red slow blink. Elrs module works fine.
Can i erase module in flashmulti when its not responding/ able to read module. Other suggestions?
Bangood Note:
"The STM32 MCU have change to ARM, fireware is ARM CORTEX-M
The new stock will be ARM, Existing inventory is not affected"
Mikael

**Comment by benlye** [comment]
Assuming you are on Windows, what device shows up in device manager when you plug the module in to your computer? You may need to update the bootloader.

You can try the troubleshooting page for some ideas:
https://github.com/benlye/flash-multi/blob/master/doc/Troubleshooting.md

**Comment by swemiklan** [comment]
I did update the bootloader and managed to update to 1.3.3.33 and could read 1 time in flashmulti then not. i was trying in transmitter and no change ( no multi telemetry detected ) message, back to flashmulti and module not recognized by computer. Can i erase module in flashmulti when its not responding/ able to read module.       Other suggestions.
I have read troubleshooting.md but dont reconize issue i have, maby same solution.

**Comment by benlye** [comment]
You can't do anything if the computer isn't recognising the module. What is showing up in device manager when you plug it in? Can you post a screenshot?

**Comment by swemiklan** [comment]
![20240823_144659](https://github.com/user-attachments/assets/87814075-22e6-49c1-9b07-3c6ce4cab665)

**Comment by benlye** [comment]
>.\tools\dfu-util-multi.exe does not exist

You don't have all the files unzipped correctly. Download the .zip file again and extract all the files, preserving the file/folder structure.

**Comment by swemiklan** [comment]
I am running window 10/11 is there a usb issue?  
Serial port maby not conecting propperly in tx, hardware issue?
Any tips on how to troubleshoot hardware ( serial port )?

**Comment by swemiklan** [comment]
Witch file to extract to where?  I am a bit lost now?

**Comment by benlye** [comment]
You have clearly downloaded FlashMulti from this site at some point, but you have not correctly extracted/expanded the .zip file (it contains the flahs-multi.exe file and also many other dependency files).

Download this file:
https://github.com/benlye/flash-multi/releases/download/0.6.1/flash-multi-0.6.1.zip

Right-click the downloaded file and choose "extract all"

Run flash-multi.exe from with the extracted folder.

**Comment by swemiklan** [comment]
Ok will try that.

Omg now i can read dfu device again. Thanks so long  still neds to conect to tx but  will start downloading 1.3.3.33 first.

**Comment by swemiklan** [comment]
Now i can see FW 1.3.3.33 on module so flash must be alright?
still not able to se firmware on Pl18 tx  and bind to rx. Thanks for your help will turn to pascallanger for further help.
